{{- define "kubernetes_apiserver-config" -}}
{{- if and .Values.datadog.collectEvents .Values.datadog.kubernetesEvents.unbundleEvents -}}
kubernetes_apiserver.yaml: |-
  init_config:
  instances:
    - unbundle_events: {{ .Values.datadog.kubernetesEvents.unbundleEvents }}
      bundle_unspecified_events: {{ .Values.datadog.kubernetesEvents.bundleUnspecifiedEvents }}
      collected_event_types:
{{ .Values.datadog.kubernetesEvents.collectedEventTypes | toYaml | nindent 8 }}
{{- end -}}
{{- end -}}
